export const contractData = {
    PLI: {
        51: {
            ADDRESS: "0xb3db178db835b4dfcb4149b2161644058393267d",
            ABI: [{ "constant": !1, "inputs": [{ "name": "spender", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "approve", "outputs": [{ "name": "", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !0, "inputs": [], "name": "totalSupply", "outputs": [{ "name": "", "type": "uint256" }], "payable": !1, "type": "function", "stateMutability": "view" }, { "constant": !1, "inputs": [{ "name": "from", "type": "address" }, { "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "transferFrom", "outputs": [{ "name": "", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !1, "inputs": [{ "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }, { "name": "data", "type": "bytes" }], "name": "transferAndCall", "outputs": [{ "name": "success", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !0, "inputs": [{ "name": "who", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "payable": !1, "type": "function", "stateMutability": "view" }, { "constant": !1, "inputs": [{ "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "transfer", "outputs": [{ "name": "", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !0, "inputs": [{ "name": "owner", "type": "address" }, { "name": "spender", "type": "address" }], "name": "allowance", "outputs": [{ "name": "", "type": "uint256" }], "payable": !1, "type": "function", "stateMutability": "view" }, { "anonymous": !1, "inputs": [{ "indexed": !0, "name": "from", "type": "address" }, { "indexed": !0, "name": "to", "type": "address" }, { "indexed": !1, "name": "value", "type": "uint256" }, { "indexed": !1, "name": "data", "type": "bytes" }], "name": "Transfer", "type": "event" }, { "anonymous": !1, "inputs": [{ "indexed": !0, "name": "owner", "type": "address" }, { "indexed": !0, "name": "spender", "type": "address" }, { "indexed": !1, "name": "value", "type": "uint256" }], "name": "Approval", "type": "event" }]
        },
        50: {
            ADDRESS: "0xff7412ea7c8445c46a8254dfb557ac1e48094391",
            ABI: [{ "constant": !1, "inputs": [{ "name": "spender", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "approve", "outputs": [{ "name": "", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !0, "inputs": [], "name": "totalSupply", "outputs": [{ "name": "", "type": "uint256" }], "payable": !1, "type": "function", "stateMutability": "view" }, { "constant": !1, "inputs": [{ "name": "from", "type": "address" }, { "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "transferFrom", "outputs": [{ "name": "", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !1, "inputs": [{ "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }, { "name": "data", "type": "bytes" }], "name": "transferAndCall", "outputs": [{ "name": "success", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !0, "inputs": [{ "name": "who", "type": "address" }], "name": "balanceOf", "outputs": [{ "name": "", "type": "uint256" }], "payable": !1, "type": "function", "stateMutability": "view" }, { "constant": !1, "inputs": [{ "name": "to", "type": "address" }, { "name": "value", "type": "uint256" }], "name": "transfer", "outputs": [{ "name": "", "type": "bool" }], "payable": !1, "type": "function", "stateMutability": "nonpayable" }, { "constant": !0, "inputs": [{ "name": "owner", "type": "address" }, { "name": "spender", "type": "address" }], "name": "allowance", "outputs": [{ "name": "", "type": "uint256" }], "payable": !1, "type": "function", "stateMutability": "view" }, { "anonymous": !1, "inputs": [{ "indexed": !0, "name": "from", "type": "address" }, { "indexed": !0, "name": "to", "type": "address" }, { "indexed": !1, "name": "value", "type": "uint256" }, { "indexed": !1, "name": "data", "type": "bytes" }], "name": "Transfer", "type": "event" }, { "anonymous": !1, "inputs": [{ "indexed": !0, "name": "owner", "type": "address" }, { "indexed": !0, "name": "spender", "type": "address" }, { "indexed": !1, "name": "value", "type": "uint256" }], "name": "Approval", "type": "event" }]
        }
    }

}

export const coingekoIds = {
    XDC: "xdce-crowd-sale",
    PLI: "plugin"
}